### ISSUE TITLE
New project fails to start

### ISSUE THREAD

**Issue by jessiahr** [boydm/scenic_new#39]
I am finally getting around to trying to get this project running on my machine but I'm getting some odd results. This is just the standard project after running `mix scenic.new.example my_app` It looks like  main_viewport exits repeatedly and then floods the Logger inbox:
```

14:46:56.421 [error] GenServer :main_viewport terminating
** (stop) exited in: GenServer.call(#PID<0.696.0>, :which_children, :infinity)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir) lib/gen_server.ex:989: GenServer.call/3
    (scenic) lib/scenic/scene.ex:1213: Scenic.Scene.do_start_child_scene/6
    (scenic) lib/scenic/view_port.ex:532: Scenic.ViewPort.handle_cast/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:set_root, {MyApp.Scene.Splash, MyApp.Scene.Sensor}, nil}}
State: %{default_scene: {MyApp.Scene.Splash, MyApp.Scene.Sensor}, default_scene_activation: nil, driver_registry: %{}, drivers: [], dynamic_root_pid: nil, dynamic_supervisor: #PID<0.695.0>, hover_primitve: nil, input_captures: %{}, master_graph: %{0 => %{data: {Scenic.Primitive.Group, [1]}, transforms: %{}}, 1 => %{data: {Scenic.Primitive.SceneRef, nil}}}, master_graph_key: {:graph, #Reference<0.1345914369.2956722177.20699>, nil}, master_styles: %{}, master_transforms: %{}, max_depth: 256, on_close: :stop_system, root_config: nil, root_graph_key: nil, root_scene_pid: nil, size: {700, 600}, supervisor: #PID<0.650.0>}

14:46:56.426 [warn]  Logger dropped 697 OTP/SASL messages as it had 1072 messages in its inbox, exceeding the amount of :discard_threshold 500 messages. The number of messages was reduced to 375 (75% of the threshold)

14:46:56.500 [error] GenServer :main_viewport terminating
** (stop) exited in: GenServer.call(#PID<0.2554.0>, :which_children, :infinity)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir) lib/gen_server.ex:989: GenServer.call/3
    (scenic) lib/scenic/scene.ex:1213: Scenic.Scene.do_start_child_scene/6
    (scenic) lib/scenic/view_port.ex:532: Scenic.ViewPort.handle_cast/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:set_root, {MyApp.Scene.Splash, MyApp.Scene.Sensor}, nil}}
State: %{default_scene: {MyApp.Scene.Splash, MyApp.Scene.Sensor}, default_scene_activation: nil, driver_registry: %{}, drivers: [], dynamic_root_pid: nil, dynamic_supervisor: #PID<0.2553.0>, hover_primitve: nil, input_captures: %{}, master_graph: %{0 => %{data: {Scenic.Primitive.Group, [1]}, transforms: %{}}, 1 => %{data: {Scenic.Primitive.SceneRef, nil}}}, master_graph_key: {:graph, #Reference<0.1345914369.2956722179.18355>, nil}, master_styles: %{}, master_transforms: %{}, max_depth: 256, on_close: :stop_system, root_config: nil, root_graph_key: nil, root_scene_pid: nil, size: {700, 600}, supervisor: #PID<0.2467.0>}

14:46:56.963 [error] GenServer :main_viewport terminating
** (stop) exited in: GenServer.call(#PID<0.7833.0>, :which_children, :infinity)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir) lib/gen_server.ex:989: GenServer.call/3
    (scenic) lib/scenic/scene.ex:1213: Scenic.Scene.do_start_child_scene/6
    (scenic) lib/scenic/view_port.ex:532: Scenic.ViewPort.handle_cast/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:set_root, {MyApp.Scene.Splash, MyApp.Scene.Sensor}, nil}}
State: %{default_scene: {MyApp.Scene.Splash, MyApp.Scene.Sensor}, default_scene_activation: nil, driver_registry: %{}, drivers: [], dynamic_root_pid: nil, dynamic_supervisor: #PID<0.7832.0>, hover_primitve: nil, input_captures: %{}, master_graph: %{0 => %{data: {Scenic.Primitive.Group, [1]}, transforms: %{}}, 1 => %{data: {Scenic.Primitive.SceneRef, nil}}}, master_graph_key: {:graph, #Reference<0.1345914369.2956722177.22102>, nil}, master_styles: %{}, master_transforms: %{}, max_depth: 256, on_close: :stop_system, root_config: nil, root_graph_key: nil, root_scene_pid: nil, size: {700, 600}, supervisor: #PID<0.7746.0>}

14:46:57.080 [error] GenServer :main_viewport terminating
** (stop) exited in: GenServer.call(#PID<0.9185.0>, :which_children, :infinity)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir) lib/gen_server.ex:989: GenServer.call/3
    (scenic) lib/scenic/scene.ex:1213: Scenic.Scene.do_start_child_scene/6
    (scenic) lib/scenic/view_port.ex:532: Scenic.ViewPort.handle_cast/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:set_root, {MyApp.Scene.Splash, MyApp.Scene.Sensor}, nil}}
State: %{default_scene: {MyApp.Scene.Splash, MyApp.Scene.Sensor}, default_scene_activation: nil, driver_registry: %{}, drivers: [], dynamic_root_pid: nil, dynamic_supervisor: #PID<0.9184.0>, hover_primitve: nil, input_captures: %{}, master_graph: %{0 => %{data: {Scenic.Primitive.Group, [1]}, transforms: %{}}, 1 => %{data: {Scenic.Primitive.SceneRef, nil}}}, master_graph_key: {:graph, #Reference<0.1345914369.2956722177.22291>, nil}, master_styles: %{}, master_transforms: %{}, max_depth: 256, on_close: :stop_system, root_config: nil, root_graph_key: nil, root_scene_pid: nil, size: {700, 600}, supervisor: #PID<0.9057.0>}

14:46:57.119 [error] GenServer :main_viewport terminating
** (stop) exited in: GenServer.call(#PID<0.9617.0>, :which_children, :infinity)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir) lib/gen_server.ex:989: GenServer.call/3
    (scenic) lib/scenic/scene.ex:1213: Scenic.Scene.do_start_child_scene/6
    (scenic) lib/scenic/view_port.ex:532: Scenic.ViewPort.handle_cast/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:set_root, {MyApp.Scene.Splash, MyApp.Scene.Sensor}, nil}}
State: %{default_scene: {MyApp.Scene.Splash, MyApp.Scene.Sensor}, default_scene_activation: nil, driver_registry: %{}, drivers: [], dynamic_root_pid: nil, dynamic_supervisor: #PID<0.9616.0>, hover_primitve: nil, input_captures: %{}, master_graph: %{0 => %{data: {Scenic.Primitive.Group, [1]}, transforms: %{}}, 1 => %{data: {Scenic.Primitive.SceneRef, nil}}}, master_graph_key: {:graph, #Reference<0.1345914369.2956722178.19653>, nil}, master_styles: %{}, master_transforms: %{}, max_depth: 256, on_close: :stop_system, root_config: nil, root_graph_key: nil, root_scene_pid: nil, size: {700, 600}, supervisor: #PID<0.9530.0>}
Maximum number of clients reachedMaximum number of clients reached
14:46:57.268 [info]  Application my_app exited: shutdown
Maximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reachedMaximum number of clients reached^C
BREAK: (a)bort (c)ontinue (p)roc info (i)nfo (l)oaded
       (v)ersion (k)ill (D)b-tables (d)istribution
```

Am I missing something? 
Enjoyed the demo at elixir conf 2018 btw!

**Comment by boydm** [comment]
Hi @jessiahr. There is a known issue that I need to publish the fix for. Please try pointing the scenic_driver_glfw dependency at the master version in github. If that doesn't work, let me know.

Otherwise wait a few hours as I'm hoping to get that published to hex later today.

**Comment by boydm** [comment]
Update is now on hex. Please `run scenic.new` again (or `mix dep.update scenic_driver_glfw`) and it should work.
