### ISSUE TITLE
mix deps.get errors out on rpi2 

### ISSUE THREAD

**Issue by hassanshaikley** [boydm/scenic_new#43]
Steps to reproduce:
```
$> mix scenic.new.nerves rpi_music_machine_nerves`
$> cd rpi_music_machine_nerves`
$> export MIX_TARGET=rpi2`
$> mix deps.get

** (Code.LoadError) could not load /Users/hshaikley/Repos/rpi_music_machine_nerves/config/rpi2.exs
    (elixir) lib/code.ex:1193: Code.find_file/2
    (elixir) lib/code.ex:758: Code.eval_file/2
    (mix) lib/mix/config.ex:158: anonymous fn/2 in Mix.Config.__import__!/2
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix) lib/mix/config.ex:157: Mix.Config.__import__!/2
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir) lib/code.ex:240: Code.eval_string/3
```

Environment

```
Erlang/OTP 22 [erts-10.4.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

IEx 1.9.1 (compiled with Erlang/OTP 22)
```

All on MacOS

**Comment by Eiji7** [comment]
@hassanshaikley I'm not into nerves, but from what I can see generator simply do not creates a config for `rpi2`. However there is config for `rpi3` and it looks like:

```elixir
use Mix.Config

config :example, :viewport, %{
  name: :main_viewport,
  # default_scene: {Example.Scene.Crosshair, nil},
  default_scene: {Example.Scene.SysInfo, nil},
  size: {800, 480},
  opts: [scale: 1.0],
  drivers: [
    %{
      module: Scenic.Driver.Nerves.Rpi
    },
    %{
      module: Scenic.Driver.Nerves.Touch,
      opts: [
        device: "FT5406 memory based driver",
        calibration: {{1, 0, 0}, {1, 0, 0}}
      ]
    }
  ]
}
```
The scenic driver is called `Scenic.Driver.Nerves.Rpi`, so maybe it would work on all `rpi` versions? I don't know about it. Anyway regardless of what driver you would use it looks like that default config requires from you a proper device config and `scenic.new.nerves` does not generate it for `rpi2`.

**Comment by hassanshaikley** [comment]
Thank you, that is perfect!

Now my only issue is that the touch doesn't seem to be working.

):

**Comment by Eiji7** [comment]
@hassanshaikley Please take a look at:
https://github.com/boydm/scenic_driver_nerves_touch
